steps:
  mtaBuild:
    buildTarget: 'CF'
    platform: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: '1daaf481trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'